# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-05 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('ip', models.CharField(max_length=20)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('online', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
