# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-06 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_date', models.DateTimeField(auto_now_add=True)),
                ('field_changed', models.CharField(max_length=10)),
                ('field_value', models.CharField(max_length=50, null=True)),
                ('field_old_value', models.CharField(max_length=50, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.Device')),
            ],
        ),
    ]
