# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_devicehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicehistory',
            options={'verbose_name': 'Device History', 'verbose_name_plural': 'Device History'},
        ),
    ]
