# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('chat_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
