# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20180507_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('message', models.TextField()),
                ('channel', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='notifications.Telegram')),
            ],
        ),
    ]
