#!/bin/bash

DOCKER_REPO=${DOCKER_REPO:-fopina/pokebox}
VERSION=$(cat VERSION)
echo "Build hook running"
echo "Building for x84_64..."
docker build -t $DOCKER_REPO:$VERSION \
			 -f Dockerfile .

echo "Building for arm32v6..."
curl -LO https://github.com/multiarch/qemu-user-static/releases/download/v2.12.0/qemu-arm-static
chmod a+x qemu-arm-static
docker build -f docker/Dockerfile.armbuilder -t armbuilder .
docker run --rm --privileged multiarch/qemu-user-static:register --reset
docker build -t $DOCKER_REPO:arm-$VERSION \
			 --build-arg BASE='armbuilder' \
			 -f Dockerfile .
